site_login:
    resource: "@SiteLoginBundle/Resources/config/routing.yml"
    prefix:   /

site_signin:
    resource: "@SiteSigninBundle/Resources/config/routing.yml"
    prefix:   /

site_main:
    resource: "@SiteMainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
